name: nemotron_cs_choice
class: guardrail_eval.models.choice.NemotronContentSafetyChoiceModel
task_types: [multiple_choice]
model_path: models/Nemotron-3-Content-Safety

backend_kwargs:
  dtype: bfloat16
  device: cuda
  device_map: cuda

system_prompt: ""
