name: safeqwen2_5_vl_7b_choice
class: guardrail_eval.models.choice.Qwen25VL3BInstructChoiceModel
task_types: [multiple_choice]
model_path: models/SafeQwen2.5-VL-7B

backend_kwargs:
  dtype: bfloat16
  device: cuda
  device_map: cuda

system_prompt: ""
